# Generated by Django 5.0.1 on 2024-02-10 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('address', models.TextField(blank=True)),
                ('date_reg', models.DateTimeField(default=datetime.datetime(2024, 2, 10, 7, 55, 35, 962965))),
            ],
        ),
    ]
