# Generated by Django 5.0.1 on 2024-02-10 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_reg',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 7, 57, 47, 884887)),
        ),
    ]
