# Generated by Django 5.0.1 on 2024-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2', '0003_alter_client_date_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_reg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
