# Generated by Django 5.0.1 on 2024-02-15 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2', '0008_orderstatus_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='date_add',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 22, 4, 41, 214366)),
        ),
    ]
