# Generated by Django 5.0.1 on 2024-02-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2', '0009_alter_trash_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='date_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
