# Generated by Django 5.0.1 on 2024-02-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2', '0010_alter_trash_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
