# Generated by Django 5.0.1 on 2024-02-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2', '0011_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trash',
            new_name='Basket',
        ),
    ]
