# Generated by Django 5.0.1 on 2024-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2', '0012_rename_trash_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
